# Generated by Django 6.0.4 on 2026-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
    ]
