# Generated by Django 6.0.4 on 2026-04-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_blogs_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
